modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="${mod_authors}" #optional

license="${mod_license}"#mandatory

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="placebo"
mandatory=true
versionRange="[8.5.5,)"
ordering="NONE"
side="BOTH"